python train.py \
-word-vectors ../data/penny.cbow.dim300.bin \
-dict ../data/vocab.pt \
-epoch 10 \
-batch 32 \
-device 1 \
-pos-vec-size 5 \
-ner-vec-size 5 \
-hidden-size 128 \
-optimizer Adamax \
-lr 0.005 \
-num-layers 3 \
-loss_margin 1 \
-brnn \
-rnn-type LSTM \
-multi-layer last \
-exp-name rnncnn-ranking \
-baidu-data ../drqa-classify/data/baidu_data.pt \
-train-data ../drqa-classify/data/sogou_shuffle_train.pt \
-valid-data ../drqa-classify/data/sogou_shuffle_valid.pt \
-resume_snapshot ../cnn/saved_checkpoint/1c_5window_dropout_nopretrian/1c_5window_dropout_nopretrian.best.query.pre.model
