python train.py \
-word-vectors data/penny.cbow.dim300.bin \
-epoch 10 \
-batch 32 \
-device 2 \
-pos-vec-size 5 \
-ner-vec-size 5 \
-hidden-size 128 \
-optimizer Adamax \
-lr 0.02 \
-num-layers 3 \
-brnn \
-rnn-type LSTM \
-multi-layer last \
-exp-name sim-dot-all
